/* ═══════════════════════════════════════════════════════════
   api/save.js  —  Vercel Serverless Function
   Receives updated show/contestant data from the admin,
   commits it to GitHub as public/data/data.js,
   which triggers a Vercel redeploy so everyone sees it.

   Required Vercel Environment Variables:
     GH_TOKEN   — GitHub Personal Access Token (repo scope)
     GH_OWNER   — Your GitHub username  e.g. BobMasterBillie
     GH_REPO    — Your repo name        e.g. realitytv2026
     ADMIN_HASH — SHA-256 hash of your admin password
═══════════════════════════════════════════════════════════ */

const crypto = require('crypto');

module.exports = async function handler(req, res) {
  /* ── CORS ── */
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Admin-Hash');

  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST')   return res.status(405).json({ error: 'Method not allowed' });

  /* ── AUTH: verify the admin hash sent in header ── */
  const sentHash   = req.headers['x-admin-hash'] || '';
  const serverHash = process.env.ADMIN_HASH || '';

  if (!serverHash) {
    return res.status(500).json({ error: 'Server misconfigured: ADMIN_HASH env var missing' });
  }
  if (!sentHash || sentHash.toLowerCase() !== serverHash.toLowerCase()) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  /* ── PARSE BODY ── */
  let body;
  try {
    body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
  } catch (e) {
    return res.status(400).json({ error: 'Invalid JSON body' });
  }

  const { shows, db } = body;
  if (!shows || !db) {
    return res.status(400).json({ error: 'Missing shows or db in payload' });
  }

  /* ── VALIDATE ENV ── */
  const GH_TOKEN = process.env.GH_TOKEN;
  const GH_OWNER = process.env.GH_OWNER;
  const GH_REPO  = process.env.GH_REPO;

  if (!GH_TOKEN || !GH_OWNER || !GH_REPO) {
    return res.status(500).json({ error: 'Missing GitHub env vars (GH_TOKEN, GH_OWNER, GH_REPO)' });
  }

  const FILE_PATH = 'public/data/data.js';
  const API_URL   = `https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/contents/${FILE_PATH}`;

  /* ── BUILD THE NEW data.js CONTENT ── */
  const timestamp = new Date().toISOString();
  const newContent = `/* ═══════════════════════════════════════════════════════════
   data.js  —  Reality TV Intelligence Dashboard 2026
   Auto-generated by admin save. Last updated: ${timestamp}
   DO NOT EDIT MANUALLY — use the admin panel on the site.
═══════════════════════════════════════════════════════════ */

window.SHOWS = ${JSON.stringify(shows, null, 2)};

window.DB = ${JSON.stringify(db, null, 2)};
`;

  const encoded = Buffer.from(newContent).toString('base64');

  /* ── GET CURRENT FILE SHA (required by GitHub API to update) ── */
  let currentSha = null;
  try {
    const getRes = await fetch(API_URL, {
      headers: {
        Authorization: `token ${GH_TOKEN}`,
        Accept:        'application/vnd.github.v3+json',
        'User-Agent':  'RealityTV-Dashboard',
      },
    });
    if (getRes.ok) {
      const getData = await getRes.json();
      currentSha = getData.sha;
    } else if (getRes.status !== 404) {
      const err = await getRes.text();
      return res.status(502).json({ error: 'GitHub GET failed: ' + err });
    }
  } catch (e) {
    return res.status(502).json({ error: 'GitHub GET error: ' + e.message });
  }

  /* ── COMMIT THE FILE ── */
  const commitBody = {
    message: `[dashboard] Update data — ${timestamp}`,
    content: encoded,
    ...(currentSha ? { sha: currentSha } : {}),
  };

  try {
    const putRes = await fetch(API_URL, {
      method:  'PUT',
      headers: {
        Authorization: `token ${GH_TOKEN}`,
        Accept:        'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
        'User-Agent':  'RealityTV-Dashboard',
      },
      body: JSON.stringify(commitBody),
    });

    const putData = await putRes.json();

    if (!putRes.ok) {
      return res.status(502).json({ error: 'GitHub commit failed', detail: putData.message });
    }

    return res.status(200).json({
      ok:      true,
      message: 'Saved to GitHub — Vercel will redeploy in ~30 seconds',
      sha:     putData.content?.sha,
      commit:  putData.commit?.html_url,
    });

  } catch (e) {
    return res.status(502).json({ error: 'GitHub PUT error: ' + e.message });
  }
};
